baseURL = "https://skku-swForum"
enableEmoji = true
languageCode = "en-us"
theme = "toha"
title = "SKKU Software forum"

[params]
# GitHub repo URL and branch of your site
gitBranch = 'main'
gitRepo = 'https://github.com/SKKU-SWForum/School_FAQs'

# specify whether you want to write some blog posts or not
enableBlogPost = true

# specify whether you want to show Table of Contents in reading page
enableTOC = true

[params.newsletter]
enable = false
