name: CI
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          submodules: "recursive"

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.75.1"

      - name: Build
        run: |
          hugo

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: public
          CLEAN: true
          GIT_CONFIG_EMAIL: skku-bot@skkuoverflow.com
          REPOSITORY_NAME: SKKU-SWForum/skku-swforum.github.io
          COMMIT_MESSAGE: "Update"
          SINGLE_COMMIT: true
